Adds new extension to store BMC passwords in GCD
m-lab/epoxy-extensions pull request #1
Opened 2020-10-20 20:16 UTC by nkinkade

This PR is part of resolving https://github.com/m-lab/epoxy/issues/94

Currently, setting up Google Cloud Datastore entities for BMCs is a manual process. Additionally, it is still necessary to run `configure_drac.py` for every new machine, another manual step. This PR represents the first step in automating this process by implementing a small ePoxy extension that will receive a BMC password from the stage1 boot process of a node, and then create a new GCD entity for that node (or update an existing entity). There will still be quite a few other steps to actually get this working, but this is a first step.

2020-10-21 13:38 UTC, robertodauria requested changes
This is definitely a big improvement over the existing process, thank you for working on it.

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/1#-:-MKAMVbTBNi5l1_WXKPi:bcna0qd)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @robertodauria)

___
*[bmc-store-password/Dockerfile, line 1 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/1#-MKAD4ejAsZaeYKKH5Os:-MKAD4ek1u5R9h8LUTxL:bl6rmoe) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/f7a6380fccc3a4eaf4989172f552d72cac2f76b9/bmc-store-password/Dockerfile#L1)):*
> ```Dockerfile
> FROM golang:1.14-alpine3.12
> ```

I would suggest 1.15-alpine3.12 since go 1.15 is available already - assuming upgrading doesn't cause any problems.
___
*[bmc-store-password/main.go, line 89 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/1#-MKAFW259taT_wuk5MUf:-MKAFW259taT_wuk5MUg:bikvt9p) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/f7a6380fccc3a4eaf4989172f552d72cac2f76b9/bmc-store-password/main.go#L89)):*
> ```Go
> 	bmcAddr, err := net.LookupHost(bmcHostname)
> 	if err != nil {
> 		return fmt.Errorf("Could not resolve BMC hostanme: %s", bmcHostname)
> ```

Nit: `hostanme`


<!-- Sent from Reviewable.io -->

2020-10-21 13:42 UTC, robertodauria reviewed
Also, a question: does anything guarantee that the request to set the password for `x` comes from the machine `x`? I have a feeling that this code would allow any machine on the platform to set any DRAC password as long as the request comes in the first 2 hours after boot, but I may be wrong.

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/1#-:-MKANrBv1WKw12LUMmbj:b-3zvi16)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)



<!-- Sent from Reviewable.io -->

2020-10-21 15:52 UTC, nkinkade reviewed
The request to this extension comes from ePoxy, not directly from the machine. The request to ePoxy from the machine is authenticated via a token, so the assumption, I believe, is that ePoxy has already authenticated the request from the machine. That said, the extension itself does not authenticate the request from ePoxy. Then again, nor does the token-server, which hands out tokens to be able to join the cluster. That said, the communication between ePoxy and these extensions happens over the private VPC network, so presumably for someone to be able to compromise these service they would have to compromise a the GCP project and gain access to the private network in some way and be able to generate requests to the extensions. I believe we have determined that that is not very likely, and in any case, if someone has compromised a machine or service in such a way as to have access to the private VPC network, then being able to generate k8s join tokens and fiddle with DRAC passwords in GCD is the least of our problems.

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/1#-:-MKAnz2MBpSZqR9S6pH_:bwik0ri)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[bmc-store-password/Dockerfile, line 1 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/1#-MKAD4ejAsZaeYKKH5Os:-MKAqqG0Bet7DZwXRog1:b-896fix) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/f7a6380fccc3a4eaf4989172f552d72cac2f76b9/bmc-store-password/Dockerfile#L1)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I would suggest 1.15-alpine3.12 since go 1.15 is available already - assuming upgrading doesn't cause any problems.
</blockquote></details>

Done.
___
*[bmc-store-password/main.go, line 89 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/1#-MKAFW259taT_wuk5MUf:-MKAqr0S5wxzdzOPpB80:bt2vr1b) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/f7a6380fccc3a4eaf4989172f552d72cac2f76b9/bmc-store-password/main.go#L89)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Nit: `hostanme`
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2020-10-22 15:58 UTC, robertodauria approved these changes
I believe the scenario I had in mind is not possible with this code, since it doesn't trust externally provided data other than the Hostname the request comes from (as passed by ePoxy). <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/1#-:-MKG-kmu0P2RUl2d-71o:bmx05eq)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @robertodauria)



<!-- Sent from Reviewable.io -->

2020-10-22 17:31 UTC, nkinkade commented
After your review I also added a Cloud Build config to run unit tests and test building the Docker image. [It passed](https://console.cloud.google.com/cloud-build/builds/eedcdc9a-e070-4a40-b8e1-65fe399e0b13?project=mlab-sandbox).

2020-10-22 19:46 UTC, merged