First iteration of a working prototype of an extension "server"
m-lab/epoxy-extensions pull request #8
Opened 2023-03-03 23:43 UTC by nkinkade

Currently, each extension directory in this repository is its own main
package, compiled separately, built into its own Docker image, run in
its own container, with its own port, own internal load balancer, own
systemd service unit, etc. This makes it cumbersome to add new
extensions.

This commit marks the first working prototype of building an extension
"server". The main package handles requests for all extensions. The
server will be a single process, in a single container, running on a
single port.

2023-03-06 16:30 UTC, stephen-soltesz commented
@robertodauria would you be willing to take a first pass at this change?

2023-03-07 18:40 UTC, robertodauria requested changes
I've taken a first pass :slightly_smiling_face: I'm also available on VC if it's helpful.

> Reviewed 17 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-:-NPxL22d-77gRFpW4tSH:bsee9jy)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`allocate_k8s_token/allocate_k8s_token.go` line 1 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPx5Wz54mRIBNYiXFBw:-NPx5Wz54mRIBNYiXFBx:bdwjy1h) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/allocate_k8s_token/allocate_k8s_token.go#L1)):*
> ```Go
> // allocate_k8s_token implements the epoxy extension API and provides a way for
> ```

Underscores in Go package names are generally discouraged (e.g. https://go.dev/blog/package-names or https://go.dev/doc/effective_go#package-names) -- would `tokengenerator` work here? So that `tokengenerator.New(...)` returns a `TokenGenerator`, for example.
___
*[`allocate_k8s_token/allocate_k8s_token.go` line 22 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxLwK8BhPfRXLKjTw_:-NPxLwK8BhPfRXLKjTwa:b-oz78n2) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/allocate_k8s_token/allocate_k8s_token.go#L22)):*
> ```Go
> 
> // runCommand implements the commander interface.
> type runCommand struct{}
> ```

Nit: An alternative to this approach would be passing a `commander` to `New`. The advantage would be that it enables blackbox testing (i.e. testing only exported methods, from a different package).
___
*[`allocate_k8s_token/allocate_k8s_token.go` line 25 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPx6zUT1NmOHgPkoQfw:-NPx6zUU1Y7mX7foSEkt:b-klhsxh) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/allocate_k8s_token/allocate_k8s_token.go#L25)):*
> ```Go
> 
> // Command takes a program name and arguments as parameters and hands those off
> // to exec.Command. It exists as a wrapper to exec.Command to faciliate
> ```

Typo: facilitate
___
*[`allocate_k8s_token/allocate_k8s_token.go` line 88 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxAfTKE9IlUwzJeByR:-NPxAfTL5FTz1AUKSmMV:bae8med) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/allocate_k8s_token/allocate_k8s_token.go#L88)):*
> ```Go
> 
> // New returns a partially populated k8sTokenGenerator
> func New(bindir string) *k8sTokenGenerator {
> ```

There used to be a linter warning when trying to return an unexported identifier from an exported function, but I've just checked and it isn't there anymore. :confused:
This may be inconvenient to use. The go doc for this package ends up being:
```
$  go doc ./allocate_k8s_token/
package allocate_k8s_token // import "github.com/m-lab/epoxy-extensions/allocate_k8s_token"

allocate_k8s_token implements the epoxy extension API and provides a way for
machines booting with epoxy to obtain a bootstrap token to join the cluster.

func New(bindir string) *k8sTokenGenerator
type TokenGenerator interface{ ... }
type TokenResponse struct{ ... }
```
...which does not say anything about the (exported) fields in `k8sTokenGenerator`.

If the user of `New()` only needs to call methods of k8sTokenGenerator, I suggest replacing it with the interface (`TokenGenerator`):
```
func New(bindir string) TokenGenerator
```

(This is also the same thing you have done with functions returning a `http.Handler` in handler.go, by the way :) )

If the user needs to access fields of that struct, maybe you could just export `K8sTokenGenerator`?
___
*[`bmc_store_password/bmc_store_password.go` line 1 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxIBrn3R96TZFR005B:-NPxIBrn3R96TZFR005C:b-7zjhhg) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/bmc_store_password/bmc_store_password.go#L1)):*
> ```Go
> // bmc_store_password implements the epoxy extension API and provides a way for
> ```

I suggest `passwordstore` so that `passwordstore.New()` returns a `PasswordStore`.
___
*[`bmc_store_password/bmc_store_password.go` line 23 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxIWNI-E4-Wpz3cXRP:-NPxIJlv-MaJzWMYrLWE:b-4gu6nf) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/bmc_store_password/bmc_store_password.go#L23)):*
> ```Go
> )
> 
> // password defines the interface for storing BMC passwords.
> ```

This seems more of a `PasswordStore` (or Storage)?
___
*[`bmc_store_password/bmc_store_password.go` line 28 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxJX1_EQR2zhMgzmIm:-NPxJX1_EQR2zhMgzmIn:bevgy2y) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/bmc_store_password/bmc_store_password.go#L28)):*
> ```Go
> }
> 
> type bmcPassword struct{}
> ```

Assuming all passwords will be for BMCs, what would change for different implementations is _where_ they'll be stored. This implementation uses Google Cloud Datastore, so perhaps `gcdPasswordStore`? 

(This also rings a bell - is there an implementation of a GCD password store somewhere else? bmctool?)
___
*[`bmc_store_password/bmc_store_password.go` line 65 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxIhnW4b8sQPaa8djE:-NPxIhnW4b8sQPaa8djF:b-83vvi2) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/bmc_store_password/bmc_store_password.go#L65)):*
> ```Go
> }
> 
> func New() *bmcPassword {
> ```

Please return the interface (same reason as above, especially where the struct does not have any exported field).
___
*[`handler/handler.go` line 14 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxG1BOA5oNdnSLoKoQ:-NPxG1BOA5oNdnSLoKoR:b-i2tdu0) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/handler/handler.go#L14)):*
> ```Go
> )
> 
> // k8sToken is the struct used to interact with the allocate_k8s_token package.
> ```

k8sToken is a Handler (the only method required to satisfy the `http.Handler` interface is `ServeHTTP`), so I find the naming confusing. 
What about `tokenHandler`? 
___
*[`handler/handler.go` line 37 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxDBjP0cy9FfhROtSJ:-NPxDBjP0cy9FfhROtSK:b-vr89c7) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/handler/handler.go#L37)):*
> ```Go
> 	}
> 
> 	if time.Now().UTC().Sub(ext.V1.LastBoot) > 120*time.Minute {
> ```

`time.Since` should be equivalent here (no need to `UTC()` since it's computing the difference between two timestamps). Also, please consider making `120*time.Minute` a named constant.



_Suggestion:_
```Go
time.Since(ext.V1.LastBoot)
```
___
*[`handler/handler.go` line 70 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxHziKDDEv7WTCAcpE:-NPxHziKDDEv7WTCAcpF:bbkat4b) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/handler/handler.go#L70)):*
> ```Go
> }
> 
> // bmcPassword is the struct used to interact with the bmc_store_password package.
> ```

Same comment as above, the naming clashes a bit with what it actually is.


<!-- Sent from Reviewable.io -->

2023-03-09 19:50 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/8)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`allocate_k8s_token/allocate_k8s_token.go` line 1 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPx5Wz54mRIBNYiXFBw:-NPyOzNO8EW76DixXtrt:b-gkfk8d) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/allocate_k8s_token/allocate_k8s_token.go#L1)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Underscores in Go package names are generally discouraged (e.g. https://go.dev/blog/package-names or https://go.dev/doc/effective_go#package-names) -- would `tokengenerator` work here? So that `tokengenerator.New(...)` returns a `TokenGenerator`, for example.
</blockquote></details>

I have changed the package name to simply `token`, and "bmc_store_password" simply `bmc`. This means that things now look like `token.New()`, `token.Create()`, etc. I had also renamed some of the structs and interfaces to remove redundant names. For example, it used to `k8sTokenGenerator`, but now is only `k8sGenerator`, etc.
___
*[`allocate_k8s_token/allocate_k8s_token.go` line 22 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxLwK8BhPfRXLKjTw_:-NQ2hY3v5rgGQdHJNeBx:b-txsdfd) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/allocate_k8s_token/allocate_k8s_token.go#L22)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Nit: An alternative to this approach would be passing a `commander` to `New`. The advantage would be that it enables blackbox testing (i.e. testing only exported methods, from a different package).
</blockquote></details>

Okay, I think I have made this change. You'll have to let me know if I've implemented it correctly. Thank you for this suggestion.
___
*[`allocate_k8s_token/allocate_k8s_token.go` line 25 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPx6zUT1NmOHgPkoQfw:-NQ2ht3EDfSV8ILTGn9i:b5fivdd) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/allocate_k8s_token/allocate_k8s_token.go#L25)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Typo: facilitate
</blockquote></details>

I removed this comment, along with the typo.
___
*[`allocate_k8s_token/allocate_k8s_token.go` line 88 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxAfTKE9IlUwzJeByR:-NQ6iPJw7QVC21vUv5DE:b-v9zeim) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/allocate_k8s_token/allocate_k8s_token.go#L88)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

There used to be a linter warning when trying to return an unexported identifier from an exported function, but I've just checked and it isn't there anymore. :confused:
This may be inconvenient to use. The go doc for this package ends up being:
```
$  go doc ./allocate_k8s_token/
package allocate_k8s_token // import "github.com/m-lab/epoxy-extensions/allocate_k8s_token"

allocate_k8s_token implements the epoxy extension API and provides a way for
machines booting with epoxy to obtain a bootstrap token to join the cluster.

func New(bindir string) *k8sTokenGenerator
type TokenGenerator interface{ ... }
type TokenResponse struct{ ... }
```
...which does not say anything about the (exported) fields in `k8sTokenGenerator`.

If the user of `New()` only needs to call methods of k8sTokenGenerator, I suggest replacing it with the interface (`TokenGenerator`):
```
func New(bindir string) TokenGenerator
```

(This is also the same thing you have done with functions returning a `http.Handler` in handler.go, by the way :) )

If the user needs to access fields of that struct, maybe you could just export `K8sTokenGenerator`?
</blockquote></details>

This makes sense. I have changed the return value to be just `Generator`. I renamed the interface from `TokenGenerator`, since the "Token" in `TokenGenerator` was redundant to the package name itself.
___
*[`bmc_store_password/bmc_store_password.go` line 1 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxIBrn3R96TZFR005B:-NQ6jeh184wJLlAK_cnV:b-g5wdcr) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/bmc_store_password/bmc_store_password.go#L1)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I suggest `passwordstore` so that `passwordstore.New()` returns a `PasswordStore`.
</blockquote></details>

From some package renaming from an earlier comment, I had changed the package name from `bmc_store_password` to just `bmc`. I changed the return type of `bmc.New()` to be of interface type `Password`. What do you think?
___
*[`bmc_store_password/bmc_store_password.go` line 23 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxIWNI-E4-Wpz3cXRP:-NQ6kYuTDATGqek0XmZd:byyapw2) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/bmc_store_password/bmc_store_password.go#L23)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

This seems more of a `PasswordStore` (or Storage)?
</blockquote></details>

This would result in `PasswordStore.Store()`, which seems like redundant naming. Does `Password.Store()` seem not informative enough, or maybe the interface name of `Password` itself is pretty vague and could be improved?
___
*[`bmc_store_password/bmc_store_password.go` line 28 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxJX1_EQR2zhMgzmIm:-NQ6l7bq3SCaH-siEO1d:b-zfeqdd) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/bmc_store_password/bmc_store_password.go#L28)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Assuming all passwords will be for BMCs, what would change for different implementations is _where_ they'll be stored. This implementation uses Google Cloud Datastore, so perhaps `gcdPasswordStore`? 

(This also rings a bell - is there an implementation of a GCD password store somewhere else? bmctool?)
</blockquote></details>

I changed the struct name to `gcdPassword`. What do you think? See my above comments about `Password` vs `PasswordStore`.
___
*[`bmc_store_password/bmc_store_password.go` line 65 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxIhnW4b8sQPaa8djE:-NQ6kQyJ0jP9hzBm3yM-:b-896fix) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/bmc_store_password/bmc_store_password.go#L65)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Please return the interface (same reason as above, especially where the struct does not have any exported field).
</blockquote></details>

Done.
___
*[`handler/handler.go` line 14 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxG1BOA5oNdnSLoKoQ:-NQ6mU57B85brar2Dmlf:b-5zttju) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/handler/handler.go#L14)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

k8sToken is a Handler (the only method required to satisfy the `http.Handler` interface is `ServeHTTP`), so I find the naming confusing. 
What about `tokenHandler`? 
</blockquote></details>

You're right, `tokenHandler` makes much more sense. Changed.
___
*[`handler/handler.go` line 37 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxDBjP0cy9FfhROtSJ:-NQ6o2eD-uANXVJohA5k:b-afkunm) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e [...]

2023-03-09 19:53 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/8)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`handler/handler.go` line 51 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NQ6vMje9kQWDFV7ONYz:-NQ6vMjf9GJ3-NmDP_3X:bwm28cx) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/f2d2da3375f439d810e70a8a846ff01599303361/handler/handler.go#L51)):*
> ```Go
> 	log.Println("Request:", ext.Encode())
> 
> 	commandArgs := []string{
> ```

@robertodauria: Something seems wrong about having the command arguments here in handler.go, but I'm not sure where better to put it. It seems more logical to put it in server.go by adding, for example, a new `Args` fields to the `token.K8sCommand` struct. The reason I've put it here is that it's useful to have the hostname in the token description in the cluster (even though the token only last 5m). But the hostname isn't known until we have processed the request. Do you have any thoughts?


<!-- Sent from Reviewable.io -->

2023-03-09 19:54 UTC, nkinkade reviewed
@robertodauria: Thank you for the review. I've made changes according to your feedback. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-:-NQ6w-_o8uAol0F3HJ3Q:b-y5dxn7)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria)



<!-- Sent from Reviewable.io -->

2023-03-14 13:25 UTC, robertodauria requested changes
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/8)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`allocate_k8s_token/allocate_k8s_token.go` line 38 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NQV8GpB6L_d1enWe_fR:-NQV8GpB6L_d1enWe_fS:b-yaaidp) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/f2d2da3375f439d810e70a8a846ff01599303361/allocate_k8s_token/allocate_k8s_token.go#L38)):*
> ```Go
> }
> 
> // details represents data used in responses to allocate_k8s_token extension
> ```

Typo: "Details"
___
*[`bmc_store_password/bmc_store_password.go` line 1 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxIBrn3R96TZFR005B:-NQVFaWp6YVDaS5cmkcj:b-g91t05) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/bmc_store_password/bmc_store_password.go#L1)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

From some package renaming from an earlier comment, I had changed the package name from `bmc_store_password` to just `bmc`. I changed the return type of `bmc.New()` to be of interface type `Password`. What do you think?
</blockquote></details>

Sounds good -- please also rename the folder (same for the other package).
___
*[`bmc_store_password/bmc_store_password.go` line 23 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxIWNI-E4-Wpz3cXRP:-NQVDxXqC2iMe7289RPW:b-x4li8q) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/bmc_store_password/bmc_store_password.go#L23)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

This would result in `PasswordStore.Store()`, which seems like redundant naming. Does `Password.Store()` seem not informative enough, or maybe the interface name of `Password` itself is pretty vague and could be improved?
</blockquote></details>

Hmm... the fact is this is not a `Password`, it's a place where passwords are stored, and the password (string) is an argument to `Store()`. It's a bit like `Car.Park(garage)` vs `Garage.Park(car)` (both are fine depending on the context): this reads like `Car.Park(car)`. :)

`PasswordStore.Put(hostname, password string)`?
`PasswordManager.Store(hostname, password string)`?

(I think `Put` is slightly better if any existing value is replaced, because of the semantics of the HTTP method with the same name).
___
*[`bmc_store_password/bmc_store_password.go` line 28 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxJX1_EQR2zhMgzmIm:-NQVG6aVA0iKfi6FaE2V:bjeuesw) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/bmc_store_password/bmc_store_password.go#L28)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I changed the struct name to `gcdPassword`. What do you think? See my above comments about `Password` vs `PasswordStore`.
</blockquote></details>

Resolving this comment to keep the discussion in one place.
___
*[`handler/handler.go` line 9 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NQV977eDxtlaKwfV3Kg:-NQV977eDxtlaKwfV3Kh:b-be06ty) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/f2d2da3375f439d810e70a8a846ff01599303361/handler/handler.go#L9)):*
> ```Go
> 	"time"
> 
> 	token "github.com/m-lab/epoxy-extensions/allocate_k8s_token"
> ```

Why? The package name is `token` already. Same for the next line.
___
*[`handler/handler.go` line 51 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NQ6vMje9kQWDFV7ONYz:-NQVA6Rs4w6_qRW6YbWL:b-1odqjb) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/f2d2da3375f439d810e70a8a846ff01599303361/handler/handler.go#L51)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

@robertodauria: Something seems wrong about having the command arguments here in handler.go, but I'm not sure where better to put it. It seems more logical to put it in server.go by adding, for example, a new `Args` fields to the `token.K8sCommand` struct. The reason I've put it here is that it's useful to have the hostname in the token description in the cluster (even though the token only last 5m). But the hostname isn't known until we have processed the request. Do you have any thoughts?
</blockquote></details>

IIUC, your feeling is correct -- this seems to violate separation of concerns. I would probably move this list of arguments to the token generator. My reasoning here is:

- The handler processes an incoming request for a hostname, and extracts the username
- The handler uses a `token.Generator` to generate a valid token for the requested hostname through its `Create` method.
- Does the handler need to know how this specific `token.Generator` implementation generates the token for the hostname? (likely not)
- If we decided to generate a token by querying a remote API in the future, would this code need to be changed? If it does not deal with the specifics of how the current `token.Generator` works, such a change would only mean calling a different implementation of `token.Generator` that knows how to talk to the remote API.
- OK, let's make the handler generator-agnostic by moving the details of the command-line token generator to the `token` package and changing `Create`to only have one argument (the hostname).


<!-- Sent from Reviewable.io -->

2023-03-14 18:37 UTC, nkinkade reviewed
@robertodauria: I have made some changes according to your feedback, as well as asked a few clarifying questions. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-:-NQWPPi33bduwrVjGQ23:b-k4ph78)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`allocate_k8s_token/allocate_k8s_token.go` line 38 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NQV8GpB6L_d1enWe_fR:-NQVkNbqACcxlpk6xp55:b-886gsx) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/f2d2da3375f439d810e70a8a846ff01599303361/allocate_k8s_token/allocate_k8s_token.go#L38)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Typo: "Details"
</blockquote></details>

Fixed
___
*[`bmc_store_password/bmc_store_password.go` line 1 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxIBrn3R96TZFR005B:-NQVkXdf5vn9924NJf-I:b5m0lf4) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/bmc_store_password/bmc_store_password.go#L1)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Sounds good -- please also rename the folder (same for the other package).
</blockquote></details>

To be sure I understand, you mean renaming the package directory `bmc_store_password/` to just `bmc/`, and renaming `allocate_k8s_token/` to just `token/`? I can do this, and it would make more logical sense for the naming and code. The only hesitation I have is losing a naming relationship between the code and the actual extension names. Extensions have these "names", as in this these are the names that ePoxy knows the extensions by and they are hard-coded into ePoxy, and the request URLs by hosts use these names as well:

https://github.com/m-lab/epoxy/blob/main/storage/extensions.go#L39

We could change the hard-coded names in ePoxy, and update ePoxy datastore entities to use these new, short names? My concern there is that the names are too terse, and properly convey what they do. For example, and extension named just `bmc`, doesn't contain any hint about what it actually does.

In your view, is it fine for us to lose a direct correlation between and extension name and it's Go package directory. I guess the way it is now, there is already a disconnect between the Go package name and the extension name, but I was trying to maintain at least a correlation between the package directory name and the extension name.

What are your thoughts?
___
*[`bmc_store_password/bmc_store_password.go` line 23 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxIWNI-E4-Wpz3cXRP:-NQWNS2a146rllWKygTF:b108wde) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/bmc_store_password/bmc_store_password.go#L23)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Hmm... the fact is this is not a `Password`, it's a place where passwords are stored, and the password (string) is an argument to `Store()`. It's a bit like `Car.Park(garage)` vs `Garage.Park(car)` (both are fine depending on the context): this reads like `Car.Park(car)`. :)

`PasswordStore.Put(hostname, password string)`?
`PasswordManager.Store(hostname, password string)`?

(I think `Put` is slightly better if any existing value is replaced, because of the semantics of the HTTP method with the same name).
</blockquote></details>

I renamed the interface to `PasswordStore` and its one method to `Put()`. 
___
*[`handler/handler.go` line 9 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NQV977eDxtlaKwfV3Kg:-NQVmmbD6mgvC_CrUvYy:b-qoxwsz) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/f2d2da3375f439d810e70a8a846ff01599303361/handler/handler.go#L9)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Why? The package name is `token` already. Same for the next line.
</blockquote></details>

I was just trying to be explicit so that anyone looking at the code would immediately know that the package directory allocate_k8s_token was exporting a package named just "token". Should I remove this and just let anyone looking at the code figure out on their own where the package name "token" is coming from in the imports?
___
*[`handler/handler.go` line 51 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NQ6vMje9kQWDFV7ONYz:-NQWLG23AvasCVfI9QMP:b-73g2ja) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/f2d2da3375f439d810e70a8a846ff01599303361/handler/handler.go#L51)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

IIUC, your feeling is correct -- this seems to violate separation of concerns. I would probably move this list of arguments to the token generator. My reasoning here is:

- The handler processes an incoming request for a hostname, and extracts the username
- The handler uses a `token.Generator` to generate a valid token for the requested hostname through its `Create` method.
- Does the handler need to know how this specific `token.Generator` implementation generates the token for the hostname? (likely not)
- If we decided to generate a token by querying a remote API in the future, would this code need to be changed? If it does not deal with the specifics of how the current `token.Generator` works, such a change would only mean calling a different implementation of `token.Generator` that knows how to talk to the remote API.
- OK, let's make the handler generator-agnostic by moving the details of the command-line token generator to the `token` package and changing `Create`to only have one argument (the hostname).
</blockquote></details>

I couldn't think of a clean way to add the command arguments to the token package, so what I did was to add an `Args` field to the `k8sGenerator` struct, and now `token.New()` expects an `args` parameter. The command arguments are now defined in server.go.

The one down side of this approach is that the for the actual kubeadm command, the command's `--description` flag value no longer has the actual hostname, which could possibly be useful for debug purposes. I think it's probably okay, since the token lifetime is only 5m anyway, and anyone debugging will be able to use timestamps to determine, more or less, which token came from which request.

Am I missing an obvious, better solution?


<!-- Sent from Reviewable.io -->

2023-03-16 21:29 UTC, nkinkade reviewed
@robertodauria: During our VC about this PR we had discussed removing the `handler` package, and moving its contents to each respective package. As I started to do that, something didn't feel quite right about that, so I left the `handler` package. I did, however, do some renaming of the interfaces and structs in the `token` package to hopefully be more intuitive.

If you still feel it would make much more sense to have the things in `handler` live in each extension package, then maybe we could do another VC to discuss this?

PTAL? Thanks!

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-:-NQgJP5-A0XDoMVZ9alL:bolsm2a)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`bmc_store_password/bmc_store_password.go` line 1 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NPxIBrn3R96TZFR005B:-NQgIKdp0jJ4aLQOckVm:bhon8cu) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/0da136b0575fc7759872c0dbf0d1f196e6557eb3/bmc_store_password/bmc_store_password.go#L1)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

To be sure I understand, you mean renaming the package directory `bmc_store_password/` to just `bmc/`, and renaming `allocate_k8s_token/` to just `token/`? I can do this, and it would make more logical sense for the naming and code. The only hesitation I have is losing a naming relationship between the code and the actual extension names. Extensions have these "names", as in this these are the names that ePoxy knows the extensions by and they are hard-coded into ePoxy, and the request URLs by hosts use these names as well:

https://github.com/m-lab/epoxy/blob/main/storage/extensions.go#L39

We could change the hard-coded names in ePoxy, and update ePoxy datastore entities to use these new, short names? My concern there is that the names are too terse, and properly convey what they do. For example, and extension named just `bmc`, doesn't contain any hint about what it actually does.

In your view, is it fine for us to lose a direct correlation between and extension name and it's Go package directory. I guess the way it is now, there is already a disconnect between the Go package name and the extension name, but I was trying to maintain at least a correlation between the package directory name and the extension name.

What are your thoughts?


</blockquote></details>

We had a chat on a VC, and decided to renamed "allocate_k8s_token" to just "token", and "bmc_store_password" to just "bmc".  Today these packages just do a single thing with regard to tokens and BMCs, but in the future they could do other operations pertaining to those things, so the short names may make sense. I have renamed the directories and files.
___
*[`handler/handler.go` line 9 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NQV977eDxtlaKwfV3Kg:-NQgIolJ512dA2BfcxKa:b-ycw3nm) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/f2d2da3375f439d810e70a8a846ff01599303361/handler/handler.go#L9)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I was just trying to be explicit so that anyone looking at the code would immediately know that the package directory allocate_k8s_token was exporting a package named just "token". Should I remove this and just let anyone looking at the code figure out on their own where the package name "token" is coming from in the imports?
</blockquote></details>

Now that the directories for these packages match the package names, I removed this aliasing and things should make more sense.
___
*[`handler/handler.go` line 51 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-NQ6vMje9kQWDFV7ONYz:-NQgIw_h97WRsRVdtrIM:b4ks3du) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/f2d2da3375f439d810e70a8a846ff01599303361/handler/handler.go#L51)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I couldn't think of a clean way to add the command arguments to the token package, so what I did was to add an `Args` field to the `k8sGenerator` struct, and now `token.New()` expects an `args` parameter. The command arguments are now defined in server.go.

The one down side of this approach is that the for the actual kubeadm command, the command's `--description` flag value no longer has the actual hostname, which could possibly be useful for debug purposes. I think it's probably okay, since the token lifetime is only 5m anyway, and anyone debugging will be able to use timestamps to determine, more or less, which token came from which request.

Am I missing an obvious, better solution?
</blockquote></details>

The  command arguments are now a global variable (`commandArgs`) in the package `token`. `token.Create()` appends the strings "--description"  and "Allow <host> to join the cluster" to `commandArgs`. 


<!-- Sent from Reviewable.io -->

2023-03-17 16:36 UTC, robertodauria approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with the addition of the tests we discussed on VC

> Reviewed 1 of 18 files at r1, 1 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-:-NQkQR4W0NPow7oyU5Pt:b-tqxfa0)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2023-03-17 20:48 UTC, nkinkade reviewed
@robertodauria: I added all the unit test we talked about, and a few others. All packages except metrics now have 100% test coverage. In order to make this work, however, I had to alias `net.LookupHost()` to a global variable. I didn't like the idea of actually relying on real DNS lookups, and using some domain like google.com. Using a domain of, say, "google.com" would cause `host.Parse()` to fail, among other things. 

Please take one last look at what I've done?

Thanks!

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-:-NQlJg4pE6-3pFM99SyJ:b-o9k70e)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2023-03-20 13:29 UTC, robertodauria approved these changes
Still <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> :)

> Reviewed 2 of 7 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/8#-:-NQzCE-f9s2Q-blQkIm7:b-gb69ru)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2023-03-21 20:03 UTC, merged