Adds new "delete" package for machines to leave the cluster
m-lab/epoxy-extensions pull request #9
Opened 2023-06-29 22:25 UTC by nkinkade

This PR adds a new service to the extension server which allows machines to request to be removed from the cluster. This is especially important for machines which are part of a MIG, where the auto-scaler might scale out and in the number of VMs in the group, there by leaving orphaned k8s nodes with no backing VM.

VMs will have a systemd service and corresponding script which will call this new extension just before shutdown.

The PR also also fixes a small bug in the token package where a global variable was continually appended to for the life of the process.

2023-07-03 12:42 UTC, robertodauria requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/9)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`server.go` line 60 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQjwYs2IBWH76-bzO0:-NZQjwYs2IBWH76-bzO1:bwh9a6n) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/server.go#L60)):*
> ```Go
> 			handler.NewBmcHandler(bmcPasswordStore)))
> 
> 	http.HandleFunc("/v1/delete_node",
> ```

fyi: This would have been a nice use case for the RESTful approach (`DELETE /v1/node/$NODE_NAME` instead of POST and querystring parameters) -- but variables in the URL aren't supported by the standard HTTP library, AFAIK. :(
___
*[`delete/delete.go` line 1 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQeIBz3neXHwaisKFP:-NZQeIBz3neXHwaisKFQ:bxbp8ag) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/delete/delete.go#L1)):*
> ```Go
> // delete implements the ePoxy extension API and provides a way for nodes to
> ```

Not a fan of the name. It feels like a reserved word (even if it's not) and it's a verb. Maybe `nodemanager` or just `node` (meant to be possibly extended in future to do more than just deleting a node from the cluster) would work here?
___
*[`delete/delete.go` line 23 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQa38V-EYFxxfK3GOA:-NZQa38V-EYFxxfK3GOB:bc4vhav) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/delete/delete.go#L23)):*
> ```Go
> 
> // DeleteCommand implements the Commander interface.
> type DeleteCommand struct{}
> ```

This ends up being used as `delete.DeleteCommand`, which stutters. How about just `Command`? The `Command` method might then become `Run` or `Exec`.
Or, if you rename the package -- see below -- this can keep its current name.
___
*[`delete/delete.go` line 31 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQcRPw-dBTB19QPB65:-NZQayqWAacNgVOhkW0m:b-8d8f41) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/delete/delete.go#L31)):*
> ```Go
> 
> // Manager defines the interface for deleting a node.
> type Manager interface {
> ```

`Manager` is a very generic name for something that only deletes (and this is enforced by the package's name, `delete`).

I see two options:
- Renaming to`Deleter` or `Deletable`
- Renaming the extension's package to `node  or `nodemanager` (with the idea that it will possibly do more than just deleting in the future)
___
*[`delete/delete.go` line 49 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQfUfL582BwU9cb9We:-NZQfUfM3ghDTgesagAL:bhhotzh) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/delete/delete.go#L49)):*
> ```Go
> 	// Delete the node
> 	output, err := d.Commander.Command(d.Command, args...)
> 	log.Println(string(output))
> ```

I suggest using a leveled logger or adding a command-line flag for verbose output.
___
*[`delete/delete.go` line 57 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQfubA3a2Hzq5P2yOu:-NZQfubA3a2Hzq5P2yOv:b4uva63) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/delete/delete.go#L57)):*
> ```Go
> }
> 
> // New returns a DeleteManager.
> ```

If a `New` func doesn't return the package's main type it's generally better to name it `NewSomething` to avoid confusion. For example, if you rename the package to `node` (or `nodemanager`), `node.New()` returning a `Node` (or `DeletableNode`) feels very natural. The same is true if you name the package `nodemanager` and `New()` returns a `NodeManager`.
___
*[`handler/handler.go` line 30 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQbzoN14ncD8L5gCzt:-NZQbzoN14ncD8L5gCzu:b-ih5fmu) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/handler/handler.go#L30)):*
> ```Go
> 	var body []byte
> 
> 	log.Println(req.RequestURI)
> ```

Have these `Println` been added intentionally? (And, will they make the logs too verbose during normal usage?)
___
*[`handler/handler.go` line 173 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQiLBYE6luvmQh2bbC:-NZQiLBYE6luvmQh2bbD:b-l0y61a) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/handler/handler.go#L173)):*
> ```Go
> 	}
> 
> 	log.Println("Request:", ext.Encode())
> ```

Same question about verbosity as above.
___
*[`metrics/metrics.go` line 47 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQkgqEAXB5pwQuMVD4:-NZQkgqEAXB5pwQuMVD5:bt4m7cj) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/metrics/metrics.go#L47)):*
> ```Go
> 			Help: "Request status codes and execution times.",
> 			Buckets: []float64{
> 				0.001, 0.01, 0.1, 1.0, 5.0, 10.0, 30.0, 60.0, 120.0, 300.0, math.Inf(+1),
> ```

What are the lower/upper time bounds for a delete command? 0.001 and 300 seconds seem a bit extreme...


<!-- Sent from Reviewable.io -->

2023-07-28 18:13 UTC, nkinkade reviewed
Thank you for the valuable feedback on this PR. Indeed, the package name `node` does make a lot more sense. I have renamed the package and made some updates to make it easy to extend the package in the future to support other node operations. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-:-NaSgnXx7HgPMDA_MzKy:b-l8k9kw)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`handler/handler.go` line 30 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQbzoN14ncD8L5gCzt:-NaSgB_t1y-GomOfocV_:b-yhcv7t) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/handler/handler.go#L30)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Have these `Println` been added intentionally? (And, will they make the logs too verbose during normal usage?)
</blockquote></details>

I added these extra log messages to make looking at the logs more useful. Previously you generally only saw the JSON that was sent in the POST request, and it was sometimes hard to know which URL was actually requested. The extension-server is not very busy. Requests to the extension-server basically only happen when a node boots or shuts down, and in practice on the platform this isn't very frequently.  Each node reboots at least every 60 days (auto reboots). That is, I don't think adding this small extra bit of verbosity will create a problem with managing or reading the logs, but will be very useful in debugging anything.
___
*[`handler/handler.go` line 173 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQiLBYE6luvmQh2bbC:-NaSgEmX1Au4LK2fbbwo:bcqchk7) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/handler/handler.go#L173)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Same question about verbosity as above.
</blockquote></details>

See my response above. Adding a few extra lines of logging makes the logs a lot more useful, and I don't anticipate it will pollute the logs. Not having the extra logging was fine when all the only thing this did was allocate_k8s_token. But now that it supports bmc operations and node operations, the extra logging helps to differentiate between request types.
___
*[`metrics/metrics.go` line 47 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQkgqEAXB5pwQuMVD4:-NaSfrffE_3I4Wo2C-zk:bdqdw68) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/metrics/metrics.go#L47)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

What are the lower/upper time bounds for a delete command? 0.001 and 300 seconds seem a bit extreme...
</blockquote></details>

I don't know. I simply used the same pattern of buckets that was used by the original author for allocate_k8s_token. We don't currently even collect these metrics. I'm open to other, more sensible values. Suggestions?
___
*[`delete/delete.go` line 1 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQeIBz3neXHwaisKFP:-NaSeAaz9AaofxEg2Kii:b-vrll3s) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/delete/delete.go#L1)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Not a fan of the name. It feels like a reserved word (even if it's not) and it's a verb. Maybe `nodemanager` or just `node` (meant to be possibly extended in future to do more than just deleting a node from the cluster) would work here?
</blockquote></details>

I change the name of the package to simply `node`.  The new package currently only implements a `Delete()` function, but could easily be extended in the future to support other "node" operations (labeling, tainting, etc.)
___
*[`delete/delete.go` line 23 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQa38V-EYFxxfK3GOA:-NaSeS2m2RABIg9WnpRQ:b-mm4p03) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/delete/delete.go#L23)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

This ends up being used as `delete.DeleteCommand`, which stutters. How about just `Command`? The `Command` method might then become `Run` or `Exec`.
Or, if you rename the package -- see below -- this can keep its current name.
</blockquote></details>

I changed it to simply `Command`, which with the renamed package will now read as `node.Command`, which does indeed seem better.
___
*[`delete/delete.go` line 31 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQcRPw-dBTB19QPB65:-NaSe_hnAyuqeXbJHUPP:b1ys9rg) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/delete/delete.go#L31)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

`Manager` is a very generic name for something that only deletes (and this is enforced by the package's name, `delete`).

I see two options:
- Renaming to`Deleter` or `Deletable`
- Renaming the extension's package to `node  or `nodemanager` (with the idea that it will possibly do more than just deleting in the future)
</blockquote></details>

I renamed the package to "node", and now `Manager` seems acceptably generic, since the package could manage any number of aspects of the node.
___
*[`delete/delete.go` line 49 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQfUfL582BwU9cb9We:-NaSgbmU--kiBgRilO1v:b-hsi9qr) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/delete/delete.go#L49)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I suggest using a leveled logger or adding a command-line flag for verbose output.
</blockquote></details>

My opinion is that this little bit of extra logging won't overwhelm the logs and should be on always. The extension server is not busy.
___
*[`delete/delete.go` line 57 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQfubA3a2Hzq5P2yOu:-NaSfaOl9BMesd97ZMhJ:bk5md8a) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/delete/delete.go#L57)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

If a `New` func doesn't return the package's main type it's generally better to name it `NewSomething` to avoid confusion. For example, if you rename the package to `node` (or `nodemanager`), `node.New()` returning a `Node` (or `DeletableNode`) feels very natural. The same is true if you name the package `nodemanager` and `New()` returns a `NodeManager`.
</blockquote></details>

Does this work now that the package has been renamed to "node", or would it still be better as, for example, `NewNodeManager()`?


<!-- Sent from Reviewable.io -->

2023-07-28 19:30 UTC, stephen-soltesz reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/9)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @robertodauria)

___
*[`handler/handler.go` line 113 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSuKWTAYG7CDzKBJOd:-NaSuKWTAYG7CDzKBJOe:bns5o7p) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/handler/handler.go#L113)):*
> ```Go
> 	}
> 
> 	log.Println("Request:", ext.Encode())
> ```

Does the `RequestURI` and `ext` message include information that obviously relate them to one another? e.g. the node name? Even if the log volume is low, relying on that to correlate interleaving requests could be error prone.
___
*[`metrics/metrics.go` line 47 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQkgqEAXB5pwQuMVD4:-NaSnveDDfyjvQS2RNcl:bcgg5al) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/metrics/metrics.go#L47)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I don't know. I simply used the same pattern of buckets that was used by the original author for allocate_k8s_token. We don't currently even collect these metrics. I'm open to other, more sensible values. Suggestions?
</blockquote></details>

I recommend removing 60, 120 & 300. We can add more if needed.
___
*[`node/node.go` line 20 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSxVDfCTEx4CNSiMjr:-NaSxVDfCTEx4CNSiMjs:bxkfzqa) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L20)):*
> ```Go
> 
> // Command implements the Commander interface.
> type Command struct{}
> ```

I recommend the `Command` type include the binary, e.g. `bindir + "/kubectl"`.

This way the `node.Manager` could include multiple, self-contained 'Command's that each do one thing well.

For example:
```
node.Manager{
   Delete: Command{Name: bindir + "/kubectl"},
   
}
```
___
*[`node/node.go` line 32 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSr4wi9jIDQtbtWUI9:-NaSr4wi9jIDQtbtWUIA:bnly28c) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L32)):*
> ```Go
> }
> 
> // NodeManager implements the Manager interface.
> ```

nit: node.NodeManager is an awkward name.

I recommend removing the node.Manager interface in favor of renaming `NodeManager` simply `Manager`.

And, updating `New` to `NewManager` which returns a `*node.Manager`.

If the server handler logic needs an interface for testing, the interface should be defined in that package not this one.
___
*[`node/node.go` line 35 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSx1oH5G-2HTJ_5dbX:-NaSx1oH5G-2HTJ_5dbY:b-5cqpf7) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L35)):*
> ```Go
> type NodeManager struct {
> 	Command   string
> 	Commander Commander
> ```

As below, I recommend a slightly different name here:

```
type Manager struct {
    Delete Commander
}
```
___
*[`node/node.go` line 45 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSwT4_BH8eZ5mCms0i:-NaSwT4_BH8eZ5mCms0j:bkfp6a0) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L45)):*
> ```Go
> 
> 	// Delete the node
> 	output, err := n.Commander.Command(n.Command, args...)
> ```

"Yo, dawg. I heard you like commands. So I've got a commander command that takes a command." These names are too much :) 

I recommend something like: m.Delete.Run(args...)` or similar. If the binary name is part of the underlying Command, the first parameter is unnecessary.
___
*[`node/node.go` line 55 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSsx4x5UflrOw9fIM6:-NaSsx4x5UflrOw9fIM7:b-roifr6) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L55)):*
https://google.github.io/styleguide/go/decisions#interfaces

> Go interfaces generally belong in the package that _consumes_ values of the interface type, not a package that _implements_ the interface type.

I would also cite the content of "See GoTip #49: Accept Interfaces, Return Concrete Types", but that appears to be a dead link in the public resource. There are exceptions to that guidance (and it's not consistently done in the M-Lab codebase) but this is a case where returning the concrete type is preferable.


<!-- Sent from Reviewable.io -->

2023-07-31 17:53 UTC, nkinkade reviewed
@stephen-soltesz: Thank  you for the review. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-:-Nah4Mfl6cTRwFP1TnrR:bobkyhs)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria and @stephen-soltesz)

___
*[`handler/handler.go` line 113 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSuKWTAYG7CDzKBJOd:-NaT5AM53Vv1TsDYPjue:bm78yfc) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/handler/handler.go#L113)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does the `RequestURI` and `ext` message include information that obviously relate them to one another? e.g. the node name? Even if the log volume is low, relying on that to correlate interleaving requests could be error prone.
</blockquote></details>

It doesn't. From what I can tell, the only fields that are ever filled in are "hostname" and "last_boot". For example, here are two `ext` messages:

```
2023/07/28 17:50:36 /v1/node/delete
2023/07/28 17:50:36 Request: {
    "v1": {
        "hostname": "mlab1-chs0t.mlab-sandbox.measurement-lab.org-f95f",
        "ipv4_address": "",
        "ipv6_address": "",
        "last_boot": "2023-07-28T17:50:35.910484743Z",
        "raw_query": ""
    }
}
2023/07/28 17:50:36 node "mlab1-chs0t.mlab-sandbox.measurement-lab.org-f95f" deleted

2023/07/28 17:51:32 /v2/allocate_k8s_token
2023/07/28 17:51:32 Request: {
    "v1": {
        "hostname": "mlab1-lax0t-mlab-sandbox-measurement-lab-org-g92z",
        "ipv4_address": "",
        "ipv6_address": "",
        "last_boot": "2023-07-28T17:51:32.838455608Z",
        "raw_query": ""
    }
}

```

The `ext` data is indistinguishable, and you only understand what each was for by the context logging I added. I had not considered the interleaving of log messages, which is no doubt possible. I don't see it as a huge issue. Machines are generally only ever rebooted one at a time. I suspect that the vast majority of the time the messages will be printed in the expected order.

Is there a better way to handle this? Maybe add more context to each log message, like some sort of unique ID?
___
*[`metrics/metrics.go` line 47 at r1](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NZQkgqEAXB5pwQuMVD4:-NaT7tl07VnmHkcpnaBj:b-896fix) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/3d16d19c81eaebeed84d6aca2d4d0cac7d35b0f8/metrics/metrics.go#L47)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I recommend removing 60, 120 & 300. We can add more if needed.
</blockquote></details>

Done.
___
*[`node/node.go` line 20 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSxVDfCTEx4CNSiMjr:-Nah1pOD9C4-IIDmZfBV:b-yip4m3) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L20)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I recommend the `Command` type include the binary, e.g. `bindir + "/kubectl"`.

This way the `node.Manager` could include multiple, self-contained 'Command's that each do one thing well.

For example:
```
node.Manager{
   Delete: Command{Name: bindir + "/kubectl"},
   
}
```
</blockquote></details>

I added a `Path` field to the `Command` type.
___
*[`node/node.go` line 32 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSr4wi9jIDQtbtWUI9:-Nah1wdt0FXzY9kKm_90:b3f0mb0) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L32)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: node.NodeManager is an awkward name.

I recommend removing the node.Manager interface in favor of renaming `NodeManager` simply `Manager`.

And, updating `New` to `NewManager` which returns a `*node.Manager`.

If the server handler logic needs an interface for testing, the interface should be defined in that package not this one.
</blockquote></details>

Done, I believe.
___
*[`node/node.go` line 35 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSx1oH5G-2HTJ_5dbX:-Nah2-9M2bYtwXKkzxBW:b-78jyb9) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L35)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

As below, I recommend a slightly different name here:

```
type Manager struct {
    Delete Commander
}
```
</blockquote></details>

I implemented this a little differently to avoid the name conflict between the Delete field and Delete receiver function, and I _believe_ the outcome is still in line with what you had in mind. The struct now looks like

```
type Manager struct {
    Command Commander
}
```

... and there still exists `Manager.Delete()`
___
*[`node/node.go` line 45 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSwT4_BH8eZ5mCms0i:-Nah2Yu202cQtuGq5TyU:b-vm20g6) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L45)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

"Yo, dawg. I heard you like commands. So I've got a commander command that takes a command." These names are too much :) 

I recommend something like: m.Delete.Run(args...)` or similar. If the binary name is part of the underlying Command, the first parameter is unnecessary.
</blockquote></details>

This is embarrassing. It now look like the much more sane: `output, err := m.Command.Run(args...)`.
___
*[`node/node.go` line 55 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSsx4x5UflrOw9fIM6:-Nah2kjV56ckcoLuIxXA:b-gvq0pj) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L55)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/go/decisions#interfaces

> Go interfaces generally belong in the package that _consumes_ values of the interface type, not a package that _implements_ the interface type.

I would also cite the content of "See GoTip #49: Accept Interfaces, Return Concrete Types", but that appears to be a dead link in the public resource. There are exceptions to that guidance (and it's not consistently done in the M-Lab codebase) but this is a case where returning the concrete type is preferable.
</blockquote></details>

Is this in reference to the `Commander` interface? The Commander interface is no longer consumed in the main package, but it mostly used in the node package.

Actually, the `token` package uses an interface named `Commander` too. The implementation in that package has the same issues you pointed out in this package, but as yet uncorrected. Is there an opportunity to have a single `Commander` interface defined that can be used by any package that needs it?


<!-- Sent from Reviewable.io -->

2023-07-31 18:46 UTC, stephen-soltesz reviewed
Much better! I have a few more suggestions for how to make the tests a little simpler and other refinements to logging, and future ideas for a new package.

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-:-NahFk1TCSD8ULm-tNiO:b-drwin5)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @robertodauria)

___
*[`handler/handler.go` line 113 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSuKWTAYG7CDzKBJOd:-Nah8dSGCi8JYO9Q7SEj:b-1so58v) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/handler/handler.go#L113)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

It doesn't. From what I can tell, the only fields that are ever filled in are "hostname" and "last_boot". For example, here are two `ext` messages:

```
2023/07/28 17:50:36 /v1/node/delete
2023/07/28 17:50:36 Request: {
    "v1": {
        "hostname": "mlab1-chs0t.mlab-sandbox.measurement-lab.org-f95f",
        "ipv4_address": "",
        "ipv6_address": "",
        "last_boot": "2023-07-28T17:50:35.910484743Z",
        "raw_query": ""
    }
}
2023/07/28 17:50:36 node "mlab1-chs0t.mlab-sandbox.measurement-lab.org-f95f" deleted

2023/07/28 17:51:32 /v2/allocate_k8s_token
2023/07/28 17:51:32 Request: {
    "v1": {
        "hostname": "mlab1-lax0t-mlab-sandbox-measurement-lab-org-g92z",
        "ipv4_address": "",
        "ipv6_address": "",
        "last_boot": "2023-07-28T17:51:32.838455608Z",
        "raw_query": ""
    }
}

```

The `ext` data is indistinguishable, and you only understand what each was for by the context logging I added. I had not considered the interleaving of log messages, which is no doubt possible. I don't see it as a huge issue. Machines are generally only ever rebooted one at a time. I suspect that the vast majority of the time the messages will be printed in the expected order.

Is there a better way to handle this? Maybe add more context to each log message, like some sort of unique ID?
</blockquote></details>

Please set `log.SetFlags(log.LUTC | log.LstdFlags | log.Lshortfile)` in the main package. This will additionally print the file and line number.

Two strategies are available, either print both  the RequestURI and request body at the same time, or include some common value in both, e.g. `req.Context()`. For example, each log message could be prefixed with the req pointer: 

```
log.Printf("context %p: %s", req.Context(), req.RequestURI)
...

log.Printf("context %p: %s", req.Context(), ext.Encode)
```

Since we have multiple handlers printing the same kind of information, I would highly recommend that (even if rare today) the interleaving problem is easy to prevent now.
___
*[`handler/handler_test.go` line 297 at r3](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NahEH2m6m5vFFZVPcCh:-NahEH2m6m5vFFZVPcCi:b-pxbut0) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/17cdd853024c7238558903dcccff3114bd9db1d5/handler/handler_test.go#L297)):*
> ```Go
> }
> 
> func (fc *fakeCommand) Run(args ...string) ([]byte, error) {
> ```

Do we need a `fakeCommand`? Is it possible to create the error cases and success cases with the `node.Command` and custom Paths? e.g. using /bin/true or /bin/false or echo, or non existent commands, etc?
___
*[`handler/handler_test.go` line 314 at r3](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NahEZtTB1Kp7yYld1af:-NahEZtTB1Kp7yYld1ag:b-ysgenj) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/17cdd853024c7238558903dcccff3114bd9db1d5/handler/handler_test.go#L314)):*
> ```Go
> 		{
> 			action:  "delete",
> 			command: "fakecommand",
> ```

Is this a script not included or is this meant to be "a command-does-not-exist"-like name?

The current name is confusing to interpret the "success" case.
___
*[`node/node.go` line 35 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSx1oH5G-2HTJ_5dbX:-NahB_dw9VIwoZGsyPne:b5ivk3c) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L35)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I implemented this a little differently to avoid the name conflict between the Delete field and Delete receiver function, and I _believe_ the outcome is still in line with what you had in mind. The struct now looks like

```
type Manager struct {
    Command Commander
}
```

... and there still exists `Manager.Delete()`
</blockquote></details>

After we spoke, I imagined this could also be something like `DeleteCmd Commander` to prevent the name collision and make new commands possible in the future. Simply `Command` works too for the current use case.
___
*[`node/node.go` line 45 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSwT4_BH8eZ5mCms0i:-NahBWHZ89M8cNdvzXYU:b-ccc4wk) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L45)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

This is embarrassing. It now look like the much more sane: `output, err := m.Command.Run(args...)`.
</blockquote></details>

I only meant to be playful. Your changes are good. Thank you for the updates.
___
*[`node/node.go` line 55 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSsx4x5UflrOw9fIM6:-NahBx2N9YYL-DqQIC2h:b57ewca) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L55)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is this in reference to the `Commander` interface? The Commander interface is no longer consumed in the main package, but it mostly used in the node package.

Actually, the `token` package uses an interface named `Commander` too. The implementation in that package has the same issues you pointed out in this package, but as yet uncorrected. Is there an opportunity to have a single `Commander` interface defined that can be used by any package that needs it?
</blockquote></details>

This comment was referring to the original return value which used the (now deleted) `node.Manager` interface. Now it's a concrete type. :+1:

The opportunity I see is to have a new package for running commands that implements the Commander interface that both the token and node packages import. It's then a style choice to either strictly limit declarations of local Commander interfaces to packages that use it or to declare one in the new package that is imported where needed.

The Go style decisions guidance above would recommend two interface definitions (they're small, and this allows them to be decoupled from changes in the other), and practically we would satisfy both with the same command runner package implementation.

I would reserve these changes for a future PR.
___
*[`node/node_test.go` line 14 at r3](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NahFAAr6IkKkGmQSJIA:-NahFAAr6IkKkGmQSJIB:bkzzyxj) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/17cdd853024c7238558903dcccff3114bd9db1d5/node/node_test.go#L14)):*
> ```Go
> }
> 
> func (fc *fakeCommand) Run(args ...string) ([]byte, error) {
> ```

I would again recommend using the real `node.Command` type with no-op processes if possible.
___
*[`node/node_test.go` line 94 at r3](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NahFUfy2IbGhhb5k8ed:-NahFUfy2IbGhhb5k8ee:b-oo6qfs) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/17cdd853024c7238558903dcccff3114bd9db1d5/node/node_test.go#L94)):*
> ```Go
> }
> 
> func Test_New(t *testing.T) {
> ```

Since `NewManager` does not return an interface, is this test still needed?


<!-- Sent from Reviewable.io -->

2023-07-31 21:11 UTC, nkinkade reviewed
@stephen-soltesz: Thank you for the additional  and helpful feedback. I have made some additional commits which I hope cover your concerns. The only outstanding question, I think, is whether `Manager.Delete()` is as effective an implementation as `Manager{ DeleteCmd Commander }`, or if one is better than the other for any reason. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-:-NahmIgG5Mz6KryZN1np:b-f64oic)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria and @stephen-soltesz)

___
*[`handler/handler.go` line 113 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSuKWTAYG7CDzKBJOd:-NahhJ1_87jPgJXDBekN:bnebsfw) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/handler/handler.go#L113)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please set `log.SetFlags(log.LUTC | log.LstdFlags | log.Lshortfile)` in the main package. This will additionally print the file and line number.

Two strategies are available, either print both  the RequestURI and request body at the same time, or include some common value in both, e.g. `req.Context()`. For example, each log message could be prefixed with the req pointer: 

```
log.Printf("context %p: %s", req.Context(), req.RequestURI)
...

log.Printf("context %p: %s", req.Context(), ext.Encode)
```

Since we have multiple handlers printing the same kind of information, I would highly recommend that (even if rare today) the interleaving problem is easy to prevent now.
</blockquote></details>

Done, I believe. Thank you for the additional suggestions and explanation. You are absolutely right that it is very easy to prevent confusing interleaving of log messages today, rather than to just say that I don't expect it to be an issue.
___
*[`handler/handler_test.go` line 297 at r3](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NahEH2m6m5vFFZVPcCh:-NahhXjWB0w5WQHx7R6s:b-vjnzv) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/17cdd853024c7238558903dcccff3114bd9db1d5/handler/handler_test.go#L297)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do we need a `fakeCommand`? Is it possible to create the error cases and success cases with the `node.Command` and custom Paths? e.g. using /bin/true or /bin/false or echo, or non existent commands, etc?
</blockquote></details>

You're right! We don't need it at all. I've modified the code to just use a `&node.Command` with the `Path` set to appropriate values for testing.
___
*[`handler/handler_test.go` line 314 at r3](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NahEZtTB1Kp7yYld1af:-Nahc6tP0v2CzZ-H7wDZ:b-njhj1h) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/17cdd853024c7238558903dcccff3114bd9db1d5/handler/handler_test.go#L314)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this a script not included or is this meant to be "a command-does-not-exist"-like name?

The current name is confusing to interpret the "success" case.
</blockquote></details>

True. I can see how it is confusing. `fakeCommand.Run()` looks to see if `command` has no value, and when it doesn't returns an error. If it has a value then it just returns some meaningless bytes and nil error.  However, this point is now moot, as I have remove `fakeCommand` altogether.
___
*[`node/node.go` line 35 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSx1oH5G-2HTJ_5dbX:-NahdrLZ5JlvIwSK16ay:b-mqz4s1) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L35)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

After we spoke, I imagined this could also be something like `DeleteCmd Commander` to prevent the name collision and make new commands possible in the future. Simply `Command` works too for the current use case.
</blockquote></details>

Would it still not be easy to do this today by defining a new receiver function, e.g., `Manager.Label()`? `nodeHandler` has an `action` field, which gets passed in by main(). The nodeHandler switches on `action` to decide which receiver function of `Manager` to call. I had imagined, for example, that some other node query path could be something like `/v1/node/label`, and with this the handler would run something like `nh.manager.Label(ext.V!.Hostname)`. Maybe this set up is a poor, non-standard implementation?
___
*[`node/node.go` line 55 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSsx4x5UflrOw9fIM6:-NahdeVE5pIRlK66QoG7:b2nha9w) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L55)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This comment was referring to the original return value which used the (now deleted) `node.Manager` interface. Now it's a concrete type. :+1:

The opportunity I see is to have a new package for running commands that implements the Commander interface that both the token and node packages import. It's then a style choice to either strictly limit declarations of local Commander interfaces to packages that use it or to declare one in the new package that is imported where needed.

The Go style decisions guidance above would recommend two interface definitions (they're small, and this allows them to be decoupled from changes in the other), and practically we would satisfy both with the same command runner package implementation.

I would reserve these changes for a future PR.
</blockquote></details>

ACK
___
*[`node/node_test.go` line 14 at r3](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NahFAAr6IkKkGmQSJIA:-NahjIfQ11spP4c3SCLt:b-ee4435) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/17cdd853024c7238558903dcccff3114bd9db1d5/node/node_test.go#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I would again recommend using the real `node.Command` type with no-op processes if possible.
</blockquote></details>

You are right again. `fakeCommand` was completely unneeded here. I removed it here too.
___
*[`node/node_test.go` line 94 at r3](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NahFUfy2IbGhhb5k8ed:-NahjRhI--P6NnLSUNlL:bpl1xwp) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/17cdd853024c7238558903dcccff3114bd9db1d5/node/node_test.go#L94)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since `NewManager` does not return an interface, is this test still needed?
</blockquote></details>

True. The test didn't even make sense any longer. I removed it, though doing so reduced code coverage by about 10%, because the package is so small and `NewManager()` apparently comprises around 10% of the entire code.


<!-- Sent from Reviewable.io -->

2023-07-31 21:51 UTC, stephen-soltesz reviewed
Okay, please apply to the log context updates to all the handlers.

A few other optional suggestions.

This should be the last round. Looks good otherwise.

> Reviewed 2 of 6 files at r3, 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-:-NahvaDhB4LjlSjACRKs:b-ga0vqk)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @robertodauria)

___
*[`handler/handler.go` line 113 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSuKWTAYG7CDzKBJOd:-NahocCp7-ARRloBxrQJ:bayq3k5) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/handler/handler.go#L113)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Done, I believe. Thank you for the additional suggestions and explanation. You are absolutely right that it is very easy to prevent confusing interleaving of log messages today, rather than to just say that I don't expect it to be an issue.
</blockquote></details>

Looks good in the nodeHandler. Please use this convention in the other handler log messages also.
___
*[`node/node.go` line 35 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSx1oH5G-2HTJ_5dbX:-NahqOFBCOfRakmeIirp:b-s4a82a) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L35)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Would it still not be easy to do this today by defining a new receiver function, e.g., `Manager.Label()`? `nodeHandler` has an `action` field, which gets passed in by main(). The nodeHandler switches on `action` to decide which receiver function of `Manager` to call. I had imagined, for example, that some other node query path could be something like `/v1/node/label`, and with this the handler would run something like `nh.manager.Label(ext.V!.Hostname)`. Maybe this set up is a poor, non-standard implementation?
</blockquote></details>

I may be missing your point. I'm imagining `node.Manager` could do multiple things other than just "Delete" operations.

We have an HTTP resource name. e.g. "/v1/node/delete"
We have a receiver method name. e.g. "manager.Delete"
We have a command that runs an operation supporting a receiver method name, e.g. "manager.DeleteCmd". (currently `manager.Command`).

A similar set of names for the next operation, etc.

If we're still not on the same page, let's talk on VC.
___
*[`node/node_test.go` line 94 at r3](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NahFUfy2IbGhhb5k8ed:-Nahpb942XvCfkYgYGim:bi0msds) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/17cdd853024c7238558903dcccff3114bd9db1d5/node/node_test.go#L94)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

True. The test didn't even make sense any longer. I removed it, though doing so reduced code coverage by about 10%, because the package is so small and `NewManager()` apparently comprises around 10% of the entire code.
</blockquote></details>

Ah, in this case, I might either keep a test case for `NewManager` (the old code was still doing interface manipulations, which was my main objection) -- or change the `NewManager` parameter to be a `*Command` (rather than bindir) so you could use `NewManager` inline on line 30 during the test.


<!-- Sent from Reviewable.io -->

2023-07-31 22:52 UTC, nkinkade reviewed
@stephen-soltesz; PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-:-Nai8lyGAjr24w8rX-ve:bh6ukm)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria and @stephen-soltesz)

___
*[`handler/handler.go` line 113 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSuKWTAYG7CDzKBJOd:-Nai8BgPBlnHCpW6fxkP:b-896fix) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/handler/handler.go#L113)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Looks good in the nodeHandler. Please use this convention in the other handler log messages also.
</blockquote></details>

Done.
___
*[`node/node.go` line 35 at r2](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NaSx1oH5G-2HTJ_5dbX:-Nai6hsm9MHNZ6mFOS_T:bg54e45) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/b01a9a066c4eae6e8a7bef9d0e0c136574994b31/node/node.go#L35)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I may be missing your point. I'm imagining `node.Manager` could do multiple things other than just "Delete" operations.

We have an HTTP resource name. e.g. "/v1/node/delete"
We have a receiver method name. e.g. "manager.Delete"
We have a command that runs an operation supporting a receiver method name, e.g. "manager.DeleteCmd". (currently `manager.Command`).

A similar set of names for the next operation, etc.

If we're still not on the same page, let's talk on VC.
</blockquote></details>

We chatted about this on the Open VC, and clarified one point of confusion. The current implementation works and is okay, though is perhaps different from the way @stephen-soltesz would have implemented it.
___
*[`node/node_test.go` line 94 at r3](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NahFUfy2IbGhhb5k8ed:-Nai3F493pNJbqBgEJ7V:b913ope) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/17cdd853024c7238558903dcccff3114bd9db1d5/node/node_test.go#L94)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Ah, in this case, I might either keep a test case for `NewManager` (the old code was still doing interface manipulations, which was my main objection) -- or change the `NewManager` parameter to be a `*Command` (rather than bindir) so you could use `NewManager` inline on line 30 during the test.
</blockquote></details>

I opted for the latter, and now `NewManager()` accepts a `*Command` parameter, and testing coverage is back to 100%.


<!-- Sent from Reviewable.io -->

2023-07-31 23:01 UTC, stephen-soltesz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> - Thank you!

> Reviewed 2 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-:-Nahvwky5UzS29AxIrtu:bsjzsje)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @robertodauria)

___
*[`node/node_test.go` line 94 at r3](https://reviewable.io/reviews/m-lab/epoxy-extensions/9#-NahFUfy2IbGhhb5k8ed:-NaiAgTNBeRHgLK0zs-g:b44uc2) ([raw file](https://github.com/m-lab/epoxy-extensions/blob/17cdd853024c7238558903dcccff3114bd9db1d5/node/node_test.go#L94)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I opted for the latter, and now `NewManager()` accepts a `*Command` parameter, and testing coverage is back to 100%.
</blockquote></details>

🎉


<!-- Sent from Reviewable.io -->

2023-07-31 23:03 UTC, merged